CREATE TABLE customers (id INT PRIMARY KEY, name TEXT NOT NULL, city TEXT);
CREATE TABLE orders (id INT PRIMARY KEY, customer_id INT, total DOUBLE PRECISION, shipped BOOLEAN);
INSERT INTO customers VALUES (1, 'Asha', 'Kolkata'), (2, 'Ben', 'London'), (3, 'Chen', 'Kolkata'), (4, 'Dara', NULL);
INSERT INTO orders VALUES (10, 1, 250.5, true), (11, 1, 99.0, false), (12, 2, 40.0, true), (13, 3, 510.25, true), (14, 3, 12.0, false);
SELECT c.name, COUNT(*) AS orders, SUM(o.total) AS spent FROM customers c JOIN orders o ON o.customer_id = c.id GROUP BY c.name ORDER BY spent DESC;
SELECT c.name, o.id FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE c.city IS NULL OR c.city = 'London';
EXPLAIN SELECT name FROM customers WHERE id = 3;
EXPLAIN SELECT * FROM orders WHERE id >= 11 AND id < 14 AND shipped ORDER BY total LIMIT 2;
SELECT * FROM orders WHERE id >= 11 AND id < 14 AND shipped ORDER BY total LIMIT 2;
BEGIN;
UPDATE orders SET total = total * 2 WHERE id = 12;
SELECT total FROM orders WHERE id = 12;
ROLLBACK;
SELECT total FROM orders WHERE id = 12;
INSERT INTO customers VALUES (1, 'Dup', 'X');
SELECT city, COUNT(*), AVG(id) FROM customers GROUP BY city HAVING COUNT(*) >= 1 ORDER BY 2 DESC, city;
DELETE FROM orders WHERE NOT shipped;
SELECT COUNT(*) FROM orders;
SHOW TABLES;
